version: '3.8'

services:
  node_app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/crud
    depends_on:
      - mongo_db
    networks:
      - app_network

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
